name: Release Prd

on:
  push:
    tags:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest
    name: set up node and install app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.2.0
      - name: SetUp Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install
        run: npm ci
      - name: run tests
        run: npm test
      - name: Build aplication
        run: npm run build
      - name: Tar files
        run: tar cvfz build.tar.gz dist/
      - name: Upload Buildfiles
        uses: actions/upload-artifact@v3
        with:
          name: buildfiles-${{github.sha}}
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [install]
    name: Deploy app to git hub pages
    steps:
      - name: Download buildfiles
        uses: actions/download-artifact@v3
        with:
          name: buildfiles-${{github.sha}}
      - name: Untar files
        run: |
          tar xvfz build.tar.gz
          rm build.tar.gz
      - name: 'add .nojekyll file'
        run: |
          cd dist
          touch .nojekyll
      - name: Push app to gitlab page repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
          external_repository: benefiction/benefiction.github.io
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
