name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test:ci
      - name: Tmp save test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-cov-${{github.sha}}
          path: coverage/lcov.info
          retention-days: 1
  report:
    runs-on: ubuntu-latest
    needs: test
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Retrieve temp test coverage
        uses: actions/download-artifact@v3
        with:
          name: test-cov-${{github.sha}}
          path: ./
      - name: Check restored files
        run: ls -lisa
      - name: Download codeclimate reporter
        run: wget -O cc-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 && chmod +x cc-reporter
      - name: Prepare code coverage
        run: ./cc-reporter format-coverage --debug lcov.info -t lcov
      - name: Upload test coverage
        run: ./cc-reporter upload-coverage --debug
